name: Build and test

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package --file resource-blocker/pom.xml
      
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@v2.2.1
      with:
        mongodb_version: '4.4.11'
        mongodb_uri: ${{ secrets.MONGODB_URI }}

    - name: Run API tests
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: mvn -B test --file resource-blocker/pom.xml
